### PR TITLE
Support Apache Kylin as a source

### PR DESCRIPTION
**Pull request by shaofengshi**
Please check #76

### CODE REVIEW

**Comment by shaofengshi** [comment]
I will rebase the pull request.

**Comment by Functor10** [comment]
I encountered some small bumps when deploying the Kylin environment, which are being processed, and the PR will be reviewed as soon as possible.

**Comment by Functor10** [comment]
Hi, Dr. shaofeng. 
Is there an example of collecting metadata? I tried to import kylin metadata but reported the following error:
`Exception in thread "main" java.lang.RuntimeException: Please add db_name in `jdbcUrl`
	at com.qihoo.qsql.metadata.collect.KylinCollector.getDatabasePosition(KylinCollector.java:141)
	at com.qihoo.qsql.metadata.collect.KylinCollector.convertDatabaseValue(KylinCollector.java:43)
	at com.qihoo.qsql.metadata.collect.MetadataCollector.execute(MetadataCollector.java:92)
	at com.qihoo.qsql.metadata.collect.MetadataCollector.main(MetadataCollector.java:81)`
I have already added project_name to my jdbcUrl. My input is: 
`{"jdbcDriver": "org.apache.kylin.jdbc.Driver", "jdbcUrl": "jdbc:kylin://localhost:7070/learn_kylin", 
"jdbcUser": "ADMIN","jdbcPassword": "KYLIN"}`
thx

**Comment by shaofengshi** [comment]
I did that in this:

./bin/meta-extract -p "{"jdbcDriver": "org.apache.kylin.jdbc.Driver", "jdbcUrl": "jdbc:kylin://localhost:7070/learn_kylin", "jdbcUser": "ADMIN","jdbcPassword": "KYLIN", "dbName": "default"}" -d "kylin" -r KYLIN_SALES

**Comment by Functor10** [comment]
Thanks this PR to help Quicksql connect to a new data source, simple SQL can now run on Kylin, but also need to check whether the dialect is supported, and then need to supplement test cases. Thx again.

**Pull request merged**
